export default {
    THEME_CHANGE: "THEME_CHANGE",//主题颜色改变
    THEME_INIT: "THEME_INIT",//主题颜色初始化
    SHOW_THEME_VIEW: "SHOW_THEME_VIEW",//展示主题颜色View
    FLUSH_POPULAR_FAVORITE:"FLUSH_POPULAR_FAVORITE",

    POPULAR_REFRESH: "POPULAR_REFRESH",//最热下拉刷新
    POPULAR_REFRESH_FAIL: "POPULAR_REFRESH_FAIL",//最热下拉刷新失败
    POPULAR_REFRESH_SUCCESS: "POPULAR_REFRESH_SUCCESS",//最热下拉刷新成功
    POPULAR_LOAD_MORE_SUCCESS: "POPULAR_LOAD_MORE_SUCCESS",//最热上拉加载成功
    POPULAR_LOAD_MORE_FAIL: "POPULAR_LOAD_MORE_FAIL",//最热上拉加载失败
    //趋势
    TRENDING_FLUSH_FAVORITE: "TRENDING_FLUSH_FAVORITE",
    TRENDING_REFRESH: "TRENDING_REFRESH",
    TRENDING_REFRESH_FAIL: "TRENDING_REFRESH_FAIL",
    TRENDING_REFRESH_SUCCESS: "TRENDING_REFRESH_SUCCESS",
    TRENDING_LOAD_MORE_SUCCESS: "TRENDING_LOAD_MORE_SUCCESS",
    TRENDING_LOAD_MORE_FAIL: "TRENDING_LOAD_MORE_FAIL",
    //收藏
    FAVORITE_LOAD_DATA:"FAVORITE_LOAD_DATA",
    FAVORITE_LOAD_SUCCESS:"FAVORITE_LOAD_SUCCESS",
    FAVORITE_LOAD_FAIL:"FAVORITE_LOAD_FAIL",

    LANGUAGE_LOAD_SUCCESS:"LANGUAGE_LOAD_SUCCESS",//加载标签成功
}